name: Build Telegram Bot API Static for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        path: telegram-bot-api

    - name: Install Chocolatey and Visual Studio Build Tools
      run: |
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Workload.MSBuild --includeRecommended --includeOptional" -y
      env:
        choco: choco.exe

    - name: Setup vcpkg
      run: |
        git clone --branch master https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        dir
        .\bootstrap-vcpkg.bat -disableMetrics
        .\vcpkg.exe integrate install
        .\vcpkg.exe install gperf:x64-windows-static openssl:x64-windows-static zlib:x64-windows-static --triplet x64-windows-static
        dir installed\x64-windows-static
        cd ..
      shell: cmd

    - name: Build Telegram Bot API Statically
      run: |
        cd telegram-bot-api
        if exist build rmdir /S /Q build
        mkdir build
        cd build
        cmake -A x64 -DCMAKE_BUILD_TYPE=Release ^
              -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake ^
              -DVCPKG_TARGET_TRIPLET=x64-windows-static ^
              -DBUILD_SHARED_LIBS=OFF ^
              -DOPENSSL_USE_STATIC_LIBS=ON ^
              -DZLIB_USE_STATIC_LIBS=ON ^
              ..
        cmake --build . --target install --config Release
        dir bin
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: telegram-bot-api-windows
        path: telegram-bot-api/bin/telegram-bot-api.exe
