name: Build Telegram Bot API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ cmake libssl-dev zlib1g-dev gperf

    - name: Build Telegram Bot API
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --target install

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: telegram-bot-api
        path: /usr/local/bin/telegram-bot-api
