name: Build Telegram Bot API Static for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
      env:
        choco: choco.exe

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install gperf:x64-windows-static openssl:x64-windows-static zlib:x64-windows-static
        cd ..

    - name: Build Telegram Bot API Statically
      run: |
        Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
        mkdir build
        cd build
        cmake -A x64 -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DVCPKG_TARGET_TRIPLET=x64-windows-static \
              -DBUILD_SHARED_LIBS=OFF \
              -DCMAKE_EXE_LINKER_FLAGS="/LTCG /LINK /LIBPATH:../vcpkg/installed/x64-windows-static/lib -static -static-libgcc -static-libstdc++" \
              -DOPENSSL_USE_STATIC_LIBS=ON \
              -DZLIB_USE_STATIC_LIBS=ON \
              ..
        cmake --build . --target install --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: telegram-bot-api-windows
        path: bin/telegram-bot-api.exe
